fos_rest:
    param_fetcher_listener:  true
    routing_loader: true
    view:
        view_response_listener:  true
        failed_validation: 422
    format_listener:
        rules:
            - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }
